import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Creepster } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const creepster = Creepster({ weight: "400", variable: '--font-creepster', subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${creepster.variable} antialiased`}
      >
        {children}
        <footer className="py-6 border-t bg-gray-950 text-foreground border-gray-800">
          <div className="container mx-auto px-4 text-center text-gray-300">
            <p>Spooky AI Hackathon.</p>
            <p className="mt-2">¡Usa el poder de la IA para crear las imágenes más espeluznantes!</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
